### ISSUE TITLE
Support for edge weights

### ISSUE THREAD

**Issue by runeksvendsen** [kaizhang/haskell-igraph#2]
Hi there,

Thanks for creating this library.

I'm searching for a Haskell library that will let me play with edge-weighted directed graphs. `igraph` seems to offer this, but it only supports igraph-0.6, which I can't find.

Are there any plans to add the possibility of weighted edges (and Dijkstra's algorithm) to this library? If not, could you briefly explain what needs to be done, so I can create the PR myself?

Cheers :)

**Comment by kaizhang** [comment]
You can use edge attributes to add edge weights. For example,

```
gr :: Graph 'D Int Double
gr = fromLabeledEdges [((0,1), 2), ((0,2), 5)]
```

Then you can access the edge weights using `labEdges`. I will add the Dijkstra's algorithm when I have time. But a PR is also welcome.

**Comment by kaizhang** [comment]
The Dijkstra's algorithm was added. See 7fd6845d60af418a2888702f3b42bda6afd69442.

Usage:
```
gr :: Graph 'D Int Double
gr = fromLabeledEdges [((0,1), 2), ((0,2), 5)]

-- shortest path without weights
print $ shortestPath gr 0 2 Nothing

-- shortest path with weights
print $ shortestPath gr 0 2 (Just id)
```

TODO: write some tests.

**Comment by runeksvendsen** [comment]
I see. I didn't realize the labels were supposed to be used for information like edge weights. 

And thanks for implementing Dijkstra!
