### ISSUE TITLE
Contact from igraph team

### ISSUE THREAD

**Issue by szhorvat** [kaizhang/haskell-igraph#5]
Hello @kaizhang,

I am writing on behalf of the igraph development team. It's great to see this project, and that igraph is being exposed from more programming languages! We were not aware of haskell-igraph before.

igraph development has picked up momentum. We are aiming for a 1.0 release with a stable API, hopefully within the year. This also means that at the moment lots of breaking changes are being made. We just released version 0.9.0 with a new build system and many infrastructural improvements. It is useful for us to be aware of downstream projects, so that their needs can be taken into account when planning for 1.0. Therefore, I would like to invite you to the igraph forum at https://igraph.discourse.group/ and encourage you to give us feedback on the experience of hooking up igraph to Haskell, as well as any issues you might have encountered with version 0.9.

**Comment by kaizhang** [comment]
Hello @szhorvat,

Thank you for the invitation! I'm glad to see that 1.0 is coming! igraph is a great package and thanks for your efforts to make it available!

**Comment by szhorvat** [comment]
This is just a heads up that version 0.10 is coming this summer, and it will make a large number of breaking changes in preparation for an eventual 1.0 release. I would recommend first making the upgrade from 0.8 to 0.9, as adapting to 0.10 is going to be a bit more work. To get a preview of 0.10, you can check out the `develop` branch of the igraph GitHub repo.

**Update:** Release candidates for 0.10 are now available in GitHub releases.
